# Python standard library
import json
import os
import sys
from os import listdir
from os.path import join
# Local imports
from scripts.common import (
    allocated,
    provided,
    references,
    str_bool
)


# Final ouput files of the pipeline
rule all:
    input:
        []


# Import rules
include: join("rules", "common.smk")
include: join("rules", "hooks.smk")
